FRONTENDSCHOOL7/villains

index.html, package-lock.json, package.json, src/App.jsx, src/api/getUserPost.js, src/components/searchbar/SearchBar.jsx, src/config/api.config.js, src/config/contact.jsx, src/config/route.config.jsx, src/hooks/useGeoLocation.jsx, src/index.jsx, src/views/Home.view.jsx
- 지도 페이지에 현재 사용자의 위치 표시
- 지도 페이지에 사용자가 쓴 게시글을 커스텀 오버레이로 표시
=> [ADD] 지도 페이지 기능 추가

src/App.jsx, src/config/route.config.jsx
- 라우터 이동이 안되는 문제에 대해서 해결하였습니다.
=> [CORS] 라우터 이동 문제 해결

src/api/getUserPost.js, src/config/api.config.js, src/views/Home.view.jsx
- api 설정이 바뀌었습니다!
```jsx
async get(url, data, headers) {
return await apis.get(`${url}`, this.params(data, headers));
}
```
headers와 data를 한 번에 받는 것이 아닌 다른 인자로 받을 수 있도록 교체한 후 합쳐서 넣어주는 코드입니다!
=> [FIX] API에 헤더가 잘못 들어가는 경우 수정

src/components/Buttons.jsx, src/components/CheckBox.jsx, src/views/SignIn.view.jsx, src/views/SignUp.view.jsx, src/views/Splash.view.jsx
[FIX] Button 컴포넌트, 로그인 데이터 받아오기 수정
- Button 컴포넌트 props 받아오던 방식 -> export 개수를 늘리는 걸로 수정
- 로그인 데이터를 받아올 시, status로 성공 실패 유무 검사 식이 잘못됐던 부분 수정
- 로그인, 회원가입 페이지 PageTemplate 사용
- CheckBox 컴포넌트 구현 -> signIn, signUp 페이지 적용
- 로그인 페이지 뒤로가기 막기 구현 -> 뒤로가기 시 confirm을 통해 사용자에게 알려주고 확인시 스플래시 페이지로 넘어가기
=> [FIX] Button 컴포넌트 수정 + 로그인 오류 수정 + CheckBox 컴포넌트 추가 + 뒤로가기 막기 구현

.github/workflows/page.yml
- 로컬의 환경변수를 깃허브에 등록하여 액션 실행 시 사용가능하도록 하였습니다.
=> [ADD] 환경변수 설정

index.html
- index.html에서 환경변수를 불러오기 위해서는 `{{환경변수이름}}` 이렇게 선언해줘야한다고 합니다!
=> [MODIFY] index.html의 환경변수 수정

src/components/layout/Header.jsx
- searchbar의 대소문자를 구분하여 진행
- 기존의 searchbar의 경우 소문자로만 인식하여 소문자로만 썼으며,
- `.jsx`를 붙이면서 대문자로 가능하게 되었습니다.
=> [MODIFY] 파일 경로 수정

vite.config.js
- `.env.production`을 기준으로 base URL이 나눠지도록 설정하였습니다.
=> [MODIFY] 배포용 base URL 수정

src/App.jsx
- 정적 페이지 배포 시에 hash라우터를 사용해야 한다고 합니다...
=> [MOIDFY] 라우터 생성을 브라우저에서 해시로 교체

src/App.jsx, src/config/route.config.jsx, src/index.jsx
- 브라우저 라우터를 사용하기로 결정했습니다.
- 해당 설정에 맞게 바꾼 후 PR 올립니다!
=> [CORS] 라우터 설정 변경

index.html, src/App.jsx, src/components/Buttons.jsx, src/components/layout/Header.jsx
- 어제 PR 후 작동 확인하여 충돌해서 지워진 코드 수정했습니다!
=> [FIX] PR 후 작동 확인

src/components/Buttons.jsx, src/components/GlobalButton.jsx, src/components/PageTemplate.jsx, src/components/layout/Header.jsx, src/components/searchbar/SearchBar.jsx, src/style/theme.js, src/views/Result.view.jsx
- style/theme.js에 디자인 시스템 추가
- components/GlobalButton.jsx에서 스타일 확인 후 사용 가능!!
=> [ADD] 글로벌 스타일 추가

src/components/Buttons.jsx, src/components/GlobalButton.jsx, src/views/Result.view.jsx
- 버튼 선택하여 해당 내용으로 시간표 다시 조회해오는 기능 추가
=> [ADD] 지하철 요일 및 방향 선택 시간표 조회 기능 추가

src/api/deleteComments.api.js, src/api/getComments.api.js, src/api/getPostDetail.api.js, src/api/getPosts.api.js, src/api/postComments.api.js, src/api/postCommentsReport.api.js, src/api/postHeart.api.js, src/atoms/bottomSheetStateAtom.js, src/components/BottomSheet.jsx, src/components/FloatingButton.style.jsx, src/components/PageTemplate.jsx, src/components/feed/Comment.jsx, src/components/feed/CommentForm.jsx, src/components/feed/Feed.jsx, src/components/feed/PostCard.jsx, src/components/layout/BackHeader.jsx, src/components/layout/Header.jsx, src/config/route.config.jsx, src/hooks/useBlockToBack.js, src/views/FeedDetail.view.jsx, src/views/FeedWrite.view.jsx
- 바텀 시트 컴포넌트 추가 (리코일에서 상태관리)
- 댓글 작성자가 본인이면 바텀시트에 삭제 기능 노출
- 다른 사람의 댓글이면 바텀시트에 신고 기능 노출
=> [ADD] 댓글 삭제, 신고 기능 추가

src/api/getProductDetail.api.js, src/api/getUserDetail.api.js, src/components/Goods.jsx, src/config/pageUrlConfig.js, src/config/route.config.jsx, src/views/GoodsDetail.view.jsx
=> [ADD] 택배 상세 페이지 추가

src/api/deleteFollow.js, src/api/getFollowingList.js, src/api/getMyInfo.js, src/api/getSearchUser.js, src/api/getUserInfo.js, src/api/getUserPost.api.js, src/api/postFollow.js, src/api/updateUser.js, src/config/route.config.jsx, src/views/Home.view.jsx, src/views/Result.view.jsx
- accountname을 받지만, 인자가 없는 경우 자신의 계정을 기본값으로 설정했습니다.
- 유저 검색 api의 경우 리액트 쿼리를 사용할 수 있도록 쿼리키로 등록했습니다.
=> [ADD] 유저 페이지 관련 API 추가

index.html, jsconfig.json, vite.config.js
- 지도 api 키를 가져오지 못하고 있어 이를 수정하여 적용합니다.
=> [CORS] 빌드 관련 옵션 수정 및 api 키 적용

src/App.jsx, vite.config.js
- [  의존성, 환경 변수, 빌드 관련 코드 업데이트
- invaild hook call 에러 수정
=> [FIX] APP.jsx의 훅 콜 수정

.github/workflows/deploy.yml
=> [UPDATE] 환경변수 적용 수정

.github/workflows/deploy.yml, src/App.jsx, vite.config.js
- 환경변수 수정 및 base  url 설정으로 production 모드 시 별도의 base url로 표기
=> [CORS] 배포 관련 설정 수정

src/config/route.config.jsx, vite.config.js
- baseurl 설정을 변경했습니다.
- route path에 baseUrl을 추가했습니다.
=> [CORS] base url 설정 변경

src/config/route.config.jsx
=> [FIX] child route path 시작 부분 변경

src/config/route.config.jsx
=> [FIX] ROUTE에 BASEURL 적용하기

src/config/pageUrlConfig.js, src/config/route.config.jsx, vite.config.js
- baseURL이 `/`이나 `/villains/`로 적용되기 때문에, 세부 라우트의 가장 앞쪽에 `/`를 제외했습니다.
- 오타를 수정했습니다.
=> [FIX] BASEURL에 맞춰 라우트 수정

vite.config.js
- 베이스 url에서 `/`를 지울 경우, `production`모드에서는 다음과 같이 적용되어서 이를 수정하였습니다.
=> [FIX] BASE URL 4차 수정

src/config/route.config.jsx, vite.config.js
=> [FIX] base url 설정

src/config/pageUrlConfig.js, src/config/route.config.jsx
- baseURL을 쉽게 적용할 수 있도록 pageUrlConfig파일에서 교체했습니다.
=> [MODIFY] 페이지 라우트 수정

src/config/pageUrlConfig.js, src/config/route.config.jsx
- 스플래시 url을 `/`로 변경하여 url 리다이렉트를 최소화하였습니다.
=> [MODIFY] 스플래시 url 변경

src/api/deleteProduct.api.js, src/api/getProducts.api.js, src/api/updateProduct.api.js, src/atoms/realProductAuthorAtom.js, src/components/DropDown.jsx, src/components/Goods.jsx, src/components/SearchSub.jsx, src/components/Tanghulu.jsx, src/components/layout/PrivateLayout.jsx, src/config/pageUrlConfig.js, src/config/route.config.jsx, src/views/Goods.view.jsx, src/views/GoodsDetail.view.jsx, src/views/GoodsWrite.view.jsx
- 택배 상세 페이지 탕후루 아이콘(바텀시트 펼치기) + 바텀시트(수정,삭제) + 택배 상태 업데이트 구현 (글 작성자만 접근 가능) 
- 택배 수정 페이지 구현 (라우터 추가)
- 택배 요청 글 삭제 구현
=> [ADD] 택배 상세 페이지 + 택배 수정 페이지

src/api/getSearchUser.js, src/components/layout/BackHeader.jsx, src/components/layout/SearchLayout.jsx, src/components/searchbar/UserCard.jsx, src/components/searchbar/UserListBox.jsx, src/views/FeedDetail.view.jsx, src/views/FeedWrite.view.jsx
- 유저 검색 기능 추가
- 검색된 유저 프로필 클릭하면 해당 유저의 프로필로 이동(추후 반영)
=> [ADD] 유저 검색 기능 추가

src/components/Goods.jsx, src/components/layout/PrivateLayout.jsx, src/views/auth/SignIn.view.jsx, src/views/auth/SignUp.view.jsx, src/views/auth/Splash.view.jsx, src/views/goods/Goods.view.jsx, src/views/goods/GoodsDetail.view.jsx, src/views/goods/GoodsWrite.view.jsx
- 라우터 구조 수정시 없어진 택배 페이지 코드들 추가
- auth 페이지 스타일 수정
=> [FIX] 없어진 코드 추가

src/api/get/getFollowingList.api.js, src/api/get/getUserFollower.api.js, src/api/post/postFollow.api.js, src/api/post/postUnFollow.api.js, src/atoms/followPageStateAtom.js, src/atoms/headerBtnStateAtom.js, src/components/Buttons.jsx, src/components/Follower.jsx, src/views/auth/SignUp.view.jsx, src/views/goods/GoodsWrite.view.jsx, src/views/goods/index.view.jsx, src/views/user/ProfileFollow.view.jsx
- 택배 페이지 별 헤더 구현
- 팔로워 페이지 구현 -> 프로필 페이지랑 연동 필요
- 팔로잉 페이지 구현 -> 프로필 페이지랑 연동 필요
=> [ADD] 택배 페이지 헤더 + 팔로워,팔로잉 페이지

src/api/get/getUserInfo.api.js, src/api/get/getUserPost.api.js, src/api/loader/searchPlace.loader.js, src/atoms/profileAtom.js, src/components/PageTemplate.jsx, src/components/PageTemplate.style.js, src/components/layout/BackHeader.jsx, src/components/layout/PrivateLayout.jsx, src/components/map/TrainMap.jsx, src/views/auth/SignIn.view.jsx, src/views/goods/GoodsDetail.view.jsx, src/views/home/Home.view.jsx, src/views/home/Result.view.jsx, src/views/home/Train.view.jsx, src/views/home/index.view.jsx
=> [UPDATE] 지하철역 지도에 표시하는 기능 업데이트

src/components/PageTemplate.style.js, src/components/chat/ChatInputField.jsx, src/components/chat/ChatListItem.jsx, src/components/chat/Message.jsx, src/components/feed/Comment.jsx, src/components/layout/NavMenu.jsx, src/components/layout/PrivateLayout.jsx, src/config/pageUrlConfig.js, src/config/route.config.jsx, src/hooks/useModal.js, src/views/chat/Chat.view.jsx, src/views/chat/ChatDetail.view.jsx, src/views/chat/index.view.jsx, src/views/feed/FeedWrite.view.jsx, src/views/feed/index.view.jsx
- 채팅 리스트, 상세페이지 UI 구현
- 레이아웃 스타일 자잘한 수정
- 게시글 작성 후 usrPostAtom에 반영
=> [ADD] 채팅 페이지 UI 구현

src/components/PageTemplate.style.js, src/components/layout/NavMenu.jsx
- 스크롤바 스타일 수정
- 하단 탭 메뉴 경로 수정
- 하단 탭 메뉴 스타일 오류 수정
=> [STYLE] 페이지 레이아웃 일부 스타일 수정

src/api/get/getChatPost.api.js, src/components/DropDown.jsx, src/components/chat/ChatInputField.jsx, src/components/chat/ChatListItem.jsx, src/components/chat/Message.jsx, src/config/pageUrlConfig.js, src/views/auth/SignIn.view.jsx, src/views/chat/Chat.view.jsx, src/views/chat/ChatDetail.view.jsx, src/views/chat/index.view.jsx, src/views/goods/GoodsDetail.view.jsx
- 다른 사용자 택배 요청 게시글에서 배달 수락 버튼 -> 채팅 페이지로 이동
- 채팅 전용 게시글은 content.postId에 chat을 추가해서 등록하고, 채팅 리스트 페이지에서 필터링해서 보여줌
- 사용자가 직접 작성한 채팅 게시글에서는 삭제가 가능한 탕후루 아이콘 표시
=> [ADD] 채팅 페이지 기능 구현

src/components/map/TrainMap.jsx
- 아직 모든 지하철역이 표시되진 않지만, 지도가 아예 안 뜨는 오류는 수정했습니다!
=> [FIX] 지하철역 표시 기능 수정

src/api/get/getFollowerList.api.js, src/api/get/getFollowingList.api.js, src/components/Follower.jsx, src/components/SkeletonChatList.jsx, src/components/chat/ChatListItem.jsx, src/views/chat/Chat.view.jsx, src/views/goods/GoodsWrite.view.jsx, src/views/goods/index.view.jsx, src/views/user/ProfileFollow.view.jsx
- 팔로워 팔로잉 페이지 수정
- 택배 페이지 유저 검색 추가, 저장하기 버튼 조건식 변경
- 채팅 페이지 스켈레톤 추가
=> [FIX] 팔로워 팔로잉 페이지 수정

jsconfig.json, src/config/route.config.jsx, vite.config.js
- lazy를 이용해 코드 스플리팅 설정했습니다. 빌드 시 하나의 파일로만 만들어져서 용량이 큰 걸 여러 개의 파일로 쪼개서 빌드하도록 설정한 것입니다.
- jsconfig.json파일로 경로를 명시해야 제대로 인식하여 추가하였습니다.
=> [CORS] 라우터 재설정

src/config/route.config.jsx
=> [FIX] 라우터 자체 lazy 사용

.github/workflows/deploy.yml
=> [MODIFY] npm 설치 방법 변경

vite.config.js
=> [FIX] base Url 임시 수정

src/views/feed/Feed.view.jsx
- 피드 페이지에서 실험적으로 적용하던 무한스크롤을 기존 것으로 되돌렸습니다.
=> [MODIFY] 무한스크롤 이전으로 되돌리기

src/api/get/getProducts.api.js, src/views/auth/SignIn.view.jsx, src/views/goods/GoodsDetail.view.jsx, src/views/user/Profile.view.jsx, src/views/user/ProfileEdit.view.jsx
=> [FIX] 프로필 페이지 수정

src/views/user/ProfileFollow.view.jsx
=> [FIX] 팔로워,팔로잉 페이지 수정 #17

src/api/get/getProducts.api.js, src/components/layout/NavMenu.jsx, src/components/searchbar/UserCard.jsx, src/config/route.config.jsx, src/views/chat/index.view.jsx, src/views/feed/Feed.view.jsx, src/views/feed/index.view.jsx, src/views/goods/index.view.jsx, src/views/user/Profile.view.jsx, src/views/user/ProfileEdit.view.jsx, src/views/user/index.view.jsx
[FIX] 기능 오류들 수정
- [FIX] 기능 오류들 수정
=> [FIX] 기능 오류들 수정

src/views/goods/GoodsDetail.view.jsx
=> [STYLE] 택배 상태 색상 변경 #63

README.md
=> [ADD] 리드미 추가

README.md
=> [MODIFY] 리드미 수정

README.md, src/views/user/Profile.view.jsx, src/views/user/index.view.jsx
- 로그아웃 시 경로가 이상하여 404로 뜨는 에러를 수정했습니다.
=> [FIX] 로그아웃 후 이동 경로 수정

index.html, src/components/profile/ShareIcon.jsx, src/views/user/Profile.view.jsx
- 프로필 페이지의 공유 아이콘을 컴포넌트로 만들어서 추가하였습니다.
- 깃허브 페이지에서 https -> http api를 호출할 수 없어 임시로 보안에 취약하지만 메타태그를 추가하였습니다.
=> [ADD] 아이콘 교체 및 오픈 API - mixed contents 허용

src/components/layout/BackHeader.jsx, src/views/auth/Splash.view.jsx, src/views/feed/Feed.view.jsx, src/views/feed/FeedDetail.view.jsx, src/views/goods/GoodsWrite.view.jsx
=> [UPDATE] Icon 교체작업중

src/components/card/ImageItem.jsx, src/views/user/Profile.view.jsx, src/views/user/ProfileEdit.view.jsx, src/views/user/index.view.jsx
- 프로필 페이지의 svg 경로를 아이콘 컴포넌트로 교체했습니다.
- hotfix 이후 UI 확인이 필요합니다.
=> [FIX] 프로필 페이지 아이콘 교체

src/components/button/Buttons.jsx, src/components/button/FloatingButton.style.jsx, src/components/card/ImagePreview.jsx, src/components/card/PostItem.jsx, src/components/card/UserCard.jsx, src/components/textarea/Comment.jsx, src/views/Error.view.jsx, src/views/feed/Feed.view.jsx, src/views/feed/FeedDetail.view.jsx, src/views/feed/FeedWrite.view.jsx, src/views/feed/index.view.jsx
- 피드 페이지 아이콘 컴포넌트로 교체
- 테스트 필요함
=> [FIX] 피드 페이지 아이콘 교체
